# include <stdio.h>
# include <sys/types.h>
# include <signal.h>
# include <unistd.h>
# include <sys/wait.h>
# include <string.h>
# include <stdlib.h>
# include <assert.h>
# include <stdint.h>
# include "../constants/constants.h"
# include <stdlib.h>
# include <errno.h>
int spec_expansion(char string[LINESIZE]);
